### ISSUE TITLE
Refactor Porch Editor Fields (feature)

### ISSUE THREAD

**Issue by towerporchfest** [funcyChaos/tower-porch-fest#10]
In the menu, change 'Add New Post' to 'Add New Porch'

One the add a porch page:

- [x]  add the following text description at the top: "Complete this form to create/edit your porch entry. When you are ready to publish send an email to towerporchfest@gmail.com."
- [x] Change default title text to "Enter your porch name here"
- [x] Change "Add New Post" to "Add Porch!"
- [x] Change "Type /to choose a block" to "Describe your porch here, have fun with it!"
   - [x] Fix text also showing on performers. This ideally would have been a [bug] ticket, but that's okay. I'll also leave a comment 😝 
- [x] Lat and Longitude aren’t updating automatically
- [x] Hide Lat and Lon to porch hosts?
   - [x] Admin should be able to view and edit
- [x]  porch host User interface doesn't need to include these capabilities
   * Sponsored
   * Porta Potty
   * Info Booth
- [x] Admin needs these capabilities
  * Sponsored
  * Porta Potty
  * Info Booth
- [x] Change "Has Food" checkbox label to "My Porch will have food"  if this is checked, add field "Describe your food option including time it will be available."
- [x] Add "Kid Friendly Porch!" Checkbox
- [x] Above the Performer Selection include the text "Add up to 12 performers.  If your performer is not in the dropdown, click here to create a new performer."  (open up Add New Performer page in new screen)
- [x] Porches need ability to create performers
- [x] Include a Featured Image upload box (its too confusing to figure out how to upload featured images currently).
- [x] Default to "Image Upload" when clicking on Upload Featured Image.  [See this code snippet](https://wordpress.stackexchange.com/questions/96513/how-to-make-upload-files-selected-by-default-in-insert-media)
- [x] Porch users need permission to upload media.

**Comment by funcyChaos** [comment]
`um-capabilities` fixes porch user permission to upload

**Comment by funcyChaos** [comment]
Setting the default text for the porch title to "Enter your porch  name here". Please advise

**Comment by funcyChaos** [comment]
I fixed the porch text showing up on the performer edit page 😜

**Comment by funcyChaos** [comment]
Pulled in several updates in pr #16 
They should be active on the site and I am going to start getting the Start Here page (#15 ) setup on branch _operator-perspective_

**Comment by funcyChaos** [comment]
Closed with PR #25
