### ISSUE TITLE
[BUG] - Emails Not Sending

### ISSUE THREAD

**Issue by funcyChaos** [funcyChaos/tower-porch-fest#11]
I am curious if the site has ever been able to send emails from the server that it's on now? Or maybe ever in general?

I have gone down an sending email rabbit hole, and it seems that the easiest way to get email working is to use WP Mail to setup SMTP for us within WordPress.If someone with access to the preferred `towerporchfest` email could check that out or otherwise share the credentials, I think that will push this issue forward

**Comment by towerporchfest** [comment]
@funcyChaos I closed this issue since we resolved it by moving to the new server
