### ISSUE TITLE
Feature - Start Here Page

### ISSUE THREAD

**Issue by funcyChaos** [funcyChaos/tower-porch-fest#15]
Start Here Page should contain this text and these links

```
Greetings Porch Host!  Here are steps you should take to fill out your custom porch page:

1) Click here, and completed the form.    [here links to add a porch page]

2) Create your performers:  Click Add Performer in the menu, or click here to Add Performer.

3) Return to your Porch Page and add performers and times.

4) Send an email to towerporchinfo@gmail.com - letting us know you are ready to go live.

If things change, come back and update your porch and performers.  All porch lineups must be completed by April 1.
```

**Comment by towerporchfest** [comment]
@funcyChaos I've provided language.  Let's run this by @KayRandolph and @arthurservin

**Comment by funcyChaos** [comment]
Number 1 as it stands seems to involve two things?

`1) Click Add Porch! or click here, and completed the form.`

**Comment by towerporchfest** [comment]
No the idea was to give them two ways to get to add porch. However if we
are creating the porch for them and connecting them this would be mute.

**Comment by funcyChaos** [comment]
Closing this since I haven't heard further updates about the start here page
