### ISSUE TITLE
Refactor Performer Editor Fields (feature)

### ISSUE THREAD

**Issue by towerporchfest** [funcyChaos/tower-porch-fest#17]
Add fields from the following form: [https://docs.google.com/forms/d/1Hr_Q03vwHvD2dCo9CCnLtMpM5D-eQyHIC-NOLRIjd-o/edit](url)

**Comment by funcyChaos** [comment]
Added the fields via acf, please let me know if they are accurate and here is a pic of where they live 😛 

<img width="1660" alt="Screenshot 2024-02-04 at 8 57 05 AM" src="https://github.com/funcyChaos/tower-porch-fest/assets/72325114/0e7fbc00-d610-4ea4-8ca2-ac57d5a859c2">

**Comment by funcyChaos** [comment]
I think I can close this so I'm gonna
