### ISSUE TITLE
Porch Update Interface (FS2)

### ISSUE THREAD

**Issue by funcyChaos** [funcyChaos/tower-porch-fest#5]
Interface (admin area) for porch operator to update their porch 

- [ ] being able to select specific performers(?)
- [ ] exclude items like Porta Potty, Sponsor

There will be items that we will want to control as Admin's on a Porches page. such as Porta potty, sponsor tag... OTHERS?

**Comment by towerporchfest** [comment]
@KayRandolph @funcyChaos I merged Kay's issue into this one... which also seems to overlap with the refactor Porch Operator page.

**Comment by funcyChaos** [comment]
@towerporchfest, @KayRandolph Marking this issue for Closed. I'll reach out to you guys by the end of the week
