### ISSUE TITLE
Porch Sign Up by January 8th!

### ISSUE THREAD

**Issue by funcyChaos** [funcyChaos/tower-porch-fest#9]
We need a portal to sign porches up and be able to get to their admin view

Send porch operators their sign up links 💙 

We need some landing page intro text. I have a custom page now

- [x] Create custom landing page for Porch Operators
   - [x] #15 
   - [x] Instructions to create a porch
   - [ ] Instructions to sign waiver
   - [x] Remove Dashboard
- [x] #10

**Comment by funcyChaos** [comment]
One problem with removing the dashboard is that the link is still available and if the login expires they will get sent to the dashboard again and then redirected in a weird way.
Potentially a bug to address later, seems to be okay for now

**Comment by towerporchfest** [comment]
@funcyChaos i believe this is closed.  Only issue I've seen is the dashboard text doesn't show up on mobile.  But thats low priority
